on: push

name: Commit Message

# NOTE: Skip check on PR so as not to confuse contributors
# NOTE: Also install a PR title checker so we don't mess up merges
# NOTE: Remove commit message check to avoid to check all the historical commits
jobs:
    check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.10"
